// <auto-generated />
using System;
using FullStack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStack.Data.Migrations
{
    [DbContext(typeof(FullStackDbContext))]
    partial class FullStackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullStack.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("InvoiceDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("InvoiceDueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvoiceRefNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            InvoiceDate = new DateTimeOffset(new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice001"
                        },
                        new
                        {
                            InvoiceId = 2,
                            InvoiceDate = new DateTimeOffset(new DateTime(2020, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice002"
                        },
                        new
                        {
                            InvoiceId = 3,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice003"
                        },
                        new
                        {
                            InvoiceId = 4,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice004"
                        },
                        new
                        {
                            InvoiceId = 5,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice005"
                        },
                        new
                        {
                            InvoiceId = 6,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice006"
                        },
                        new
                        {
                            InvoiceId = 7,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice007"
                        },
                        new
                        {
                            InvoiceId = 8,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice008"
                        },
                        new
                        {
                            InvoiceId = 9,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice009"
                        },
                        new
                        {
                            InvoiceId = 10,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice010"
                        },
                        new
                        {
                            InvoiceId = 11,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice011"
                        },
                        new
                        {
                            InvoiceId = 12,
                            InvoiceDate = new DateTimeOffset(new DateTime(2021, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceDueDate = new DateTimeOffset(new DateTime(2021, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            InvoiceRefNumber = "invoice012"
                        });
                });

            modelBuilder.Entity("FullStack.Data.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            InvoiceItemId = 1,
                            Description = "Desktop Technology Support",
                            HoursWorked = 400m,
                            InvoiceId = 1,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 2,
                            Description = "Network/Server Technolody Support",
                            HoursWorked = 365m,
                            InvoiceId = 1,
                            RatePerHour = 91m
                        },
                        new
                        {
                            InvoiceItemId = 3,
                            Description = "Security patches & CMS updates",
                            HoursWorked = 200m,
                            InvoiceId = 1,
                            RatePerHour = 400m
                        },
                        new
                        {
                            InvoiceItemId = 4,
                            Description = "Desktop Technology Support",
                            HoursWorked = 300m,
                            InvoiceId = 2,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 5,
                            Description = "Desktop Technology Support",
                            HoursWorked = 200m,
                            InvoiceId = 2,
                            RatePerHour = 400m
                        },
                        new
                        {
                            InvoiceItemId = 6,
                            Description = "Advanced Technology Support",
                            HoursWorked = 487m,
                            InvoiceId = 3,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 7,
                            Description = "Security patches & CMS updates",
                            HoursWorked = 265m,
                            InvoiceId = 3,
                            RatePerHour = 578m
                        },
                        new
                        {
                            InvoiceItemId = 8,
                            Description = "After-hours maintenance",
                            HoursWorked = 1000m,
                            InvoiceId = 3,
                            RatePerHour = 1200m
                        },
                        new
                        {
                            InvoiceItemId = 9,
                            Description = "Full web maintenance",
                            HoursWorked = 300m,
                            InvoiceId = 4,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 10,
                            Description = "Security patches & CMS updates",
                            HoursWorked = 300m,
                            InvoiceId = 4,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 11,
                            Description = "Network/Server Technology",
                            HoursWorked = 300m,
                            InvoiceId = 4,
                            RatePerHour = 579m
                        },
                        new
                        {
                            InvoiceItemId = 12,
                            Description = "Premier Consulting Services",
                            HoursWorked = 300m,
                            InvoiceId = 5,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 13,
                            Description = "Desktop Technology Support",
                            HoursWorked = 300m,
                            InvoiceId = 6,
                            RatePerHour = 695m
                        },
                        new
                        {
                            InvoiceItemId = 14,
                            Description = "Desktop Technology Support",
                            HoursWorked = 987m,
                            InvoiceId = 6,
                            RatePerHour = 789m
                        },
                        new
                        {
                            InvoiceItemId = 15,
                            Description = "After-hour maintenance",
                            HoursWorked = 250m,
                            InvoiceId = 7,
                            RatePerHour = 89m
                        },
                        new
                        {
                            InvoiceItemId = 16,
                            Description = "Security patches & CMS updates",
                            HoursWorked = 200m,
                            InvoiceId = 7,
                            RatePerHour = 400m
                        },
                        new
                        {
                            InvoiceItemId = 17,
                            Description = "Security patches & CMS updates",
                            HoursWorked = 200m,
                            InvoiceId = 7,
                            RatePerHour = 400m
                        },
                        new
                        {
                            InvoiceItemId = 18,
                            Description = "Desktop Technology Support",
                            HoursWorked = 300m,
                            InvoiceId = 8,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 19,
                            Description = "Desktop Technology Support",
                            HoursWorked = 200m,
                            InvoiceId = 8,
                            RatePerHour = 400m
                        },
                        new
                        {
                            InvoiceItemId = 20,
                            Description = "Desktop Technology Support",
                            HoursWorked = 479m,
                            InvoiceId = 8,
                            RatePerHour = 9876m
                        },
                        new
                        {
                            InvoiceItemId = 21,
                            Description = "Desktop Technology Support",
                            HoursWorked = 479m,
                            InvoiceId = 8,
                            RatePerHour = 9876m
                        },
                        new
                        {
                            InvoiceItemId = 22,
                            Description = "Full web maintenance",
                            HoursWorked = 960m,
                            InvoiceId = 9,
                            RatePerHour = 400m
                        },
                        new
                        {
                            InvoiceItemId = 23,
                            Description = "Full web maintenance",
                            HoursWorked = 450m,
                            InvoiceId = 9,
                            RatePerHour = 789m
                        },
                        new
                        {
                            InvoiceItemId = 24,
                            Description = "Desktop Technology Support",
                            HoursWorked = 300m,
                            InvoiceId = 10,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 25,
                            Description = "Desktop Technology Support",
                            HoursWorked = 200m,
                            InvoiceId = 10,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 26,
                            Description = "Desktop Technology Support",
                            HoursWorked = 300m,
                            InvoiceId = 11,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 27,
                            Description = "Desktop Technology Support",
                            HoursWorked = 200m,
                            InvoiceId = 11,
                            RatePerHour = 400m
                        },
                        new
                        {
                            InvoiceItemId = 28,
                            Description = "Desktop Technology Support",
                            HoursWorked = 300m,
                            InvoiceId = 12,
                            RatePerHour = 84m
                        },
                        new
                        {
                            InvoiceItemId = 29,
                            Description = "Desktop Technology Support",
                            HoursWorked = 200m,
                            InvoiceId = 12,
                            RatePerHour = 400m
                        });
                });

            modelBuilder.Entity("FullStack.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forenames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            Forenames = "Admin",
                            Password = "administration",
                            Role = "Admin",
                            Surname = "User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anthonyCoder@gmail.com",
                            Forenames = "Anthony",
                            Password = "administration",
                            Role = "User",
                            Surname = "Coder"
                        });
                });

            modelBuilder.Entity("FullStack.Data.Entities.InvoiceItem", b =>
                {
                    b.HasOne("FullStack.Data.Entities.Invoice", null)
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
