<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FullStack.Data\FullStack.Data.csproj" />
    <ProjectReference Include="..\FullStack.ViewModels\FullStack.ViewModels.csproj" />
  </ItemGroup>

</Project>
